layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Go
    web_url: https://github.com/topics/golang
    image_url: https://raw.githubusercontent.com/github/explore/424902f9441eeb28663ad3f45e25398ac3445c79/topics/go/go.png

  - name: Nats
    web_url: https://nats.io
    image_url: https://nats.io/img/large-logo.png

  - name: Dynomite
    web_url: https://github.com/Netflix/dynomite
    image_url: https://github.com/Netflix/dynomite/raw/dev/images/dynomite-logo.png

  - name: Streaming
    web_url: https://github.com/topics/streaming

